// Code generated by go run ./cmd/wrappergen; DO NOT EDIT.
// Source: internal/contract/source/endpoints.json and service_wrappers.txt.

package aeries

import "context"

// PreEnrollService exposes command-style pre-enrollment endpoints.
type PreEnrollService struct {
	client *Client
}

// Trigger asks Aeries to run the documented student pre-enrollment action for one student.
func (s *PreEnrollService) Trigger(ctx context.Context, req PreEnrollRequest) (JSONDocument, error) {
	return s.client.doDocument(ctx, "preenroll.trigger", RequestOptions{
		PathParams: map[string]string{
			"StudentID": intString(req.StudentID),
		},
		JSONBody:     req.Values,
		DatabaseYear: req.DatabaseYear,
	})
}

// TriggerInactive creates a new pre-enrollment record from an inactive student at the requested destination school.
func (s *PreEnrollService) TriggerInactive(ctx context.Context, req PreEnrollInactiveRequest) ([]JSONDocument, error) {
	return s.client.doDocuments(ctx, "preenroll.trigger_inactive", RequestOptions{
		PathParams: map[string]string{
			"StudentID":      intString(req.StudentID),
			"NextSchoolCode": intString(req.NextSchoolCode),
		},
		DatabaseYear: req.DatabaseYear,
	})
}
