package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// endpointFile mirrors the curated endpoint inventory used by contractsync.
type endpointFile struct {
	Endpoints []endpoint `json:"endpoints"`
}

// endpoint contains the contract fields needed to render one wrapper method.
type endpoint struct {
	ID              string   `json:"id"`
	Service         string   `json:"service"`
	MethodName      string   `json:"method_name"`
	Summary         string   `json:"summary"`
	ResponseShape   string   `json:"response_shape"`
	PathParameters  []string `json:"path_parameters"`
	QueryParameters []string `json:"query_parameters"`
	Mutation        bool     `json:"mutation"`
}

// requestSpec binds a contract operation to the stable public request type that callers already use.
type requestSpec struct {
	ID      string
	Request string
	Body    string
	Comment string
}

// fieldInfo records only the type distinction the generator needs when converting request values to strings.
type fieldInfo struct {
	Integer bool
}

// serviceComments keep the service-level orientation text stable and separate from repetitive method plumbing.
var serviceComments = map[string]string{
	"Alerts":        "AlertsService exposes the documented alert send endpoint.",
	"Attendance":    "AttendanceService exposes enrollment and attendance history endpoints.",
	"CodeSets":      "CodeSetsService exposes code set lookups used by many other Aeries objects.",
	"Gradebook":     "GradebookService exposes gradebook, assignment, and score endpoints.",
	"PreEnroll":     "PreEnrollService exposes command-style pre-enrollment endpoints.",
	"Programs":      "ProgramsService exposes student program endpoints as their own beginner-friendly service.",
	"Scheduling":    "SchedulingService exposes courses, sections, rosters, and course request endpoints.",
	"Schools":       "SchoolsService exposes school-related read operations.",
	"Staff":         "StaffService exposes staff, teacher, and staff change-feed endpoints.",
	"StudentGrades": "StudentGradesService exposes GPA, report card, transcript, and graduation endpoints.",
	"Students":      "StudentsService exposes student data, contacts, testing, and other student-centered endpoints.",
	"System":        "SystemService exposes installation-wide Aeries endpoints.",
}

const generatedWrapperHeader = "// Code generated by go run ./cmd/wrappergen; DO NOT EDIT.\n"

// main delegates to run so generation and drift checks remain directly testable.
func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// run loads the three source-of-truth inputs and either writes or verifies every generated service file.
func run(args []string) error {
	flags := flag.NewFlagSet("wrappergen", flag.ContinueOnError)
	check := flags.Bool("check", false, "verify generated service wrappers without rewriting files")
	if err := flags.Parse(args); err != nil {
		return err
	}
	root, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("determine repository root: %w", err)
	}
	endpoints, err := loadEndpoints(filepath.Join(root, "internal", "contract", "source", "endpoints.json"))
	if err != nil {
		return err
	}
	specs, err := loadSpecs(filepath.Join(root, "internal", "contract", "source", "service_wrappers.txt"))
	if err != nil {
		return err
	}
	fields, err := loadRequestFields(filepath.Join(root, "requests.go"))
	if err != nil {
		return err
	}
	outputs, err := generate(endpoints, specs, fields)
	if err != nil {
		return err
	}
	existing, err := findGeneratedWrappers(root)
	if err != nil {
		return err
	}
	for _, name := range existing {
		if _, expected := outputs[name]; expected {
			continue
		}
		if *check {
			return fmt.Errorf("stale generated wrapper %s has no service in the contract inventory", name)
		}
		if err := os.Remove(filepath.Join(root, name)); err != nil {
			return fmt.Errorf("remove stale generated wrapper %s: %w", name, err)
		}
	}
	for name, content := range outputs {
		path := filepath.Join(root, name)
		if *check {
			actual, readErr := os.ReadFile(path)
			if readErr != nil {
				return fmt.Errorf("read generated wrapper %s: %w", name, readErr)
			}
			if !bytes.Equal(actual, content) {
				return fmt.Errorf("generated wrapper drift detected for %s", name)
			}
			continue
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			return fmt.Errorf("write generated wrapper %s: %w", name, err)
		}
	}
	return nil
}

// findGeneratedWrappers discovers only root Go files carrying this generator's exact ownership header.
func findGeneratedWrappers(root string) ([]string, error) {
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, fmt.Errorf("list generated wrappers: %w", err)
	}
	wrappers := []string{}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		content, err := os.ReadFile(filepath.Join(root, entry.Name()))
		if err != nil {
			return nil, fmt.Errorf("read possible generated wrapper %s: %w", entry.Name(), err)
		}
		if bytes.HasPrefix(content, []byte(generatedWrapperHeader)) {
			wrappers = append(wrappers, entry.Name())
		}
	}
	sort.Strings(wrappers)
	return wrappers, nil
}

// loadEndpoints decodes the vendored operation inventory that also drives the public contract manifest.
func loadEndpoints(path string) ([]endpoint, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read endpoint metadata: %w", err)
	}
	var file endpointFile
	if err := json.Unmarshal(data, &file); err != nil {
		return nil, fmt.Errorf("decode endpoint metadata: %w", err)
	}
	return file.Endpoints, nil
}

// loadSpecs reads the intentionally small operation-to-request mapping and rejects malformed or duplicate rows.
func loadSpecs(path string) ([]requestSpec, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open wrapper metadata: %w", err)
	}
	defer file.Close()
	var specs []requestSpec
	seen := map[string]bool{}
	scanner := bufio.NewScanner(file)
	for line := 1; scanner.Scan(); line++ {
		text := strings.TrimSpace(scanner.Text())
		if text == "" || strings.HasPrefix(text, "#") {
			continue
		}
		columns := strings.SplitN(text, "|", 2)
		parts := strings.Fields(columns[0])
		if len(parts) < 2 || len(parts) > 3 {
			return nil, fmt.Errorf("wrapper metadata line %d must contain operation id, request type, and optional body field", line)
		}
		if len(columns) != 2 || strings.TrimSpace(columns[1]) == "" {
			return nil, fmt.Errorf("wrapper metadata line %d must contain a public method comment", line)
		}
		if seen[parts[0]] {
			return nil, fmt.Errorf("duplicate wrapper metadata for %s", parts[0])
		}
		seen[parts[0]] = true
		body := ""
		if len(parts) == 3 {
			if !strings.HasPrefix(parts[2], "body=") || strings.TrimPrefix(parts[2], "body=") == "" {
				return nil, fmt.Errorf("wrapper metadata line %d has invalid body field %q", line, parts[2])
			}
			body = strings.TrimPrefix(parts[2], "body=")
		}
		specs = append(specs, requestSpec{ID: parts[0], Request: parts[1], Body: body, Comment: strings.TrimSpace(columns[1])})
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan wrapper metadata: %w", err)
	}
	return specs, nil
}

// loadRequestFields parses the public request structs so field conversions stay derived from the public contracts.
func loadRequestFields(path string) (map[string]map[string]fieldInfo, error) {
	parsed, err := parser.ParseFile(token.NewFileSet(), path, nil, 0)
	if err != nil {
		return nil, fmt.Errorf("parse public request types: %w", err)
	}
	requests := map[string]map[string]fieldInfo{}
	for _, declaration := range parsed.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok || general.Tok != token.TYPE {
			continue
		}
		for _, item := range general.Specs {
			typeSpec, ok := item.(*ast.TypeSpec)
			if !ok {
				continue
			}
			structure, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}
			fields := map[string]fieldInfo{}
			for _, field := range structure.Fields.List {
				identifier, integer := field.Type.(*ast.Ident)
				for _, name := range field.Names {
					fields[name.Name] = fieldInfo{Integer: integer && identifier.Name == "int"}
				}
			}
			requests[typeSpec.Name.Name] = fields
		}
	}
	return requests, nil
}

// generate validates complete endpoint coverage and renders one deterministic file per service.
func generate(endpoints []endpoint, specs []requestSpec, requestFields map[string]map[string]fieldInfo) (map[string][]byte, error) {
	byID := map[string]requestSpec{}
	for _, spec := range specs {
		byID[spec.ID] = spec
	}
	groups := map[string][]endpoint{}
	for _, operation := range endpoints {
		if _, ok := byID[operation.ID]; !ok {
			return nil, fmt.Errorf("endpoint %s has no wrapper request mapping", operation.ID)
		}
		groups[operation.Service] = append(groups[operation.Service], operation)
	}
	if len(byID) != len(endpoints) {
		return nil, fmt.Errorf("wrapper metadata has %d entries but contract has %d endpoints", len(byID), len(endpoints))
	}
	outputs := map[string][]byte{}
	for service, operations := range groups {
		content, err := renderService(service, operations, byID, requestFields)
		if err != nil {
			return nil, err
		}
		outputs[serviceFilename(service)] = content
	}
	return outputs, nil
}

// renderService emits readable Go wrappers while retaining the contract inventory as their canonical operation source.
func renderService(service string, operations []endpoint, specs map[string]requestSpec, requestFields map[string]map[string]fieldInfo) ([]byte, error) {
	var out strings.Builder
	out.WriteString(generatedWrapperHeader)
	out.WriteString("// Source: internal/contract/source/endpoints.json and service_wrappers.txt.\n\n")
	out.WriteString("package aeries\n\nimport \"context\"\n\n")
	serviceType := service + "Service"
	fmt.Fprintf(&out, "// %s\ntype %s struct {\n\tclient *Client\n}\n", serviceComments[service], serviceType)
	for _, operation := range operations {
		spec := specs[operation.ID]
		fields, ok := requestFields[spec.Request]
		if !ok {
			return nil, fmt.Errorf("endpoint %s references unknown request type %s", operation.ID, spec.Request)
		}
		method, err := renderMethod(serviceType, operation, spec, fields)
		if err != nil {
			return nil, err
		}
		out.WriteString(method)
	}
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated %s wrappers: %w", service, err)
	}
	return formatted, nil
}

// renderMethod builds one wrapper from path, query, response, and request-shape metadata.
func renderMethod(serviceType string, operation endpoint, spec requestSpec, fields map[string]fieldInfo) (string, error) {
	var out strings.Builder
	fmt.Fprintf(&out, "\n// %s %s\n", operation.MethodName, spec.Comment)
	returnType, helper, err := responseBinding(operation)
	if err != nil {
		return "", err
	}
	fmt.Fprintf(&out, "func (s *%s) %s(ctx context.Context, req %s) %s {\n", serviceType, operation.MethodName, spec.Request, returnType)
	queryParams := withoutDatabaseYear(operation.QueryParameters)
	_, hasFilters := fields["Filters"]
	if len(queryParams) > 0 {
		out.WriteString("\tquery := map[string]string{}\n")
		for _, parameter := range queryParams {
			field := requestField(parameter, spec.Request)
			info, ok := fields[field]
			if !ok {
				return "", fmt.Errorf("endpoint %s query parameter %s has no field on %s", operation.ID, parameter, spec.Request)
			}
			function := "addQueryValue"
			if info.Integer {
				function = "addIntQueryValue"
			}
			fmt.Fprintf(&out, "\t%s(query, %q, req.%s)\n", function, parameter, field)
		}
	}
	fmt.Fprintf(&out, "\treturn s.client.%s(ctx, %q, RequestOptions{\n", helper, operation.ID)
	if len(operation.PathParameters) > 0 {
		out.WriteString("\t\tPathParams: map[string]string{\n")
		for _, parameter := range operation.PathParameters {
			field := requestField(parameter, spec.Request)
			info, ok := fields[field]
			if !ok {
				return "", fmt.Errorf("endpoint %s path parameter %s has no field on %s", operation.ID, parameter, spec.Request)
			}
			value := "req." + field
			if info.Integer {
				value = "intString(" + value + ")"
			}
			fmt.Fprintf(&out, "\t\t\t%q: %s,\n", parameter, value)
		}
		out.WriteString("\t\t},\n")
	}
	if len(queryParams) > 0 {
		out.WriteString("\t\tQuery: query,\n")
	} else if hasFilters {
		out.WriteString("\t\tQuery: cloneMap(req.Filters),\n")
	}
	if spec.Body != "" {
		if _, ok := fields[spec.Body]; !ok {
			return "", fmt.Errorf("endpoint %s body field %s is missing from %s", operation.ID, spec.Body, spec.Request)
		}
		fmt.Fprintf(&out, "\t\tJSONBody: req.%s,\n", spec.Body)
	}
	if _, ok := fields["DatabaseYear"]; ok {
		out.WriteString("\t\tDatabaseYear: req.DatabaseYear,\n")
	}
	out.WriteString("\t})\n}\n")
	return out.String(), nil
}

// responseBinding selects the existing helper and public return contract for each documented response shape.
func responseBinding(operation endpoint) (string, string, error) {
	if operation.ID == "system.get_info" {
		return "(SystemInfo, error)", "doSystemInfo", nil
	}
	switch operation.ResponseShape {
	case "object":
		return "(JSONDocument, error)", "doDocument", nil
	case "list":
		return "([]JSONDocument, error)", "doDocuments", nil
	case "empty":
		return "error", "doNoContent", nil
	default:
		return "", "", fmt.Errorf("endpoint %s has unsupported response shape %q", operation.ID, operation.ResponseShape)
	}
}

// requestField handles the two Aeries names whose public request fields intentionally use clearer names.
func requestField(parameter string, requestType string) string {
	if parameter == "code" {
		return "ProgramCode"
	}
	if parameter == "AcademicYear" && requestType == "SchoolStringLookupRequest" {
		return "Value"
	}
	return parameter
}

// withoutDatabaseYear removes the query value supplied centrally by RequestOptions.
func withoutDatabaseYear(parameters []string) []string {
	result := make([]string, 0, len(parameters))
	for _, parameter := range parameters {
		if parameter != "DatabaseYear" {
			result = append(result, parameter)
		}
	}
	return result
}

// serviceFilename converts service names to the stable root filenames already used by the package.
func serviceFilename(service string) string {
	switch service {
	case "StudentGrades":
		return "student_grades.go"
	default:
		return strings.ToLower(service) + ".go"
	}
}
